#------------------------------------------------------------------------------------#
#                           SignClick Plugin Configuration                           #
#------------------------------------------------------------------------------------#
# This file contains the core configuration for the SignClick plugin, including its  #
# name, version, main class, commands, and permissions.                              #
#------------------------------------------------------------------------------------#

name: SignClick
version: 2.0.6
author: klanting
main: com.klanting.signclick.SignClick
api-version: 1.18

#------------------------------------------------------------------------------------#
#                                        Commands                                    #
#------------------------------------------------------------------------------------#
commands:
  signclick:
    description: all info about the signclick plugin
    usage: /<command>
  signclickpos:
    description: mark the teleport endpoint position
    usage: /<command>
  country:
    description: president commands
    usage: /<command>
  dynmap:
    description: get the dynmap.
    usage: /<command>
  weeklypay:
    description: set a payment towards a person that pays every week.
    usage: /<command>
  company:
    description: use the company commands.
    usage: /<command>
  party:
    description: use the party commands.
    usage: /<command>
#------------------------------------------------------------------------------------#
#                                      Localization                                  #
#------------------------------------------------------------------------------------#
localization:
  default: en_US
  supported: [en_US]
#------------------------------------------------------------------------------------#
#                                       Permissions                                  #
#------------------------------------------------------------------------------------#
# This section defines all the permissions for the SignClick plugin.                 #
#------------------------------------------------------------------------------------#
permissions:
  signclick.*:
    description: Allows access to all features (including staff only).
    default: op
    children:
      signclick.tp: true
      signclick.company.*: true
      signclick.country.*: true

      signclick.company.sharebal: true
      signclick.signin:
        description: Allows the player to open any sign income door

  #Sign TP
  signclick.tp:
    description: Allows making sign TP signs.
    default: true

  #------------------------------ Company Permissions ---------------------------------#
  # Permissions related to company management and interactions.                        #
  #------------------------------------------------------------------------------------#
  signclick.company.*:
    description: Allows the player company commands
    default: true
    children:
      signclick.company.create: true
      signclick.company.info: true
      signclick.company.sharetop: true
      signclick.company.give: true
      signclick.company.baltop: true
      signclick.company.buy: true
      signclick.company.sell: true
      signclick.company.pay: true
      signclick.company.spendable: true
      signclick.company.transfer: true
      signclick.company.get_support: true
      signclick.company.support: true
      signclick.company.open_trade: true
      signclick.company.markettop: true
      signclick.company.market: true
      signclick.company.menu: true
      signclick.company.portfolio: true
      signclick.company.transact: true
      signclick.company.contract: true
      signclick.company.get_buy_price: true
      signclick.company.get_sell_price: true
      signclick.company.guide: true

  #--------------------------- Company Permissions Sub area ---------------------------#
  # Permissions related to company management and interactions.                        #
  #------------------------------------------------------------------------------------#
  signclick.company.create:
    description: Allows the player to create a company
  signclick.company.info:
    description: Allows the player to retrieve info of a company
  signclick.company.sharetop:
    description: Allows the player to retrieve the list of share owners of the company
  signclick.company.give:
    description: Allows the player to give money to a company
  signclick.company.baltop:
    description: Allows the player to get a balance top of the companies
  signclick.company.buy:
    description: Allows the player to buy shares of a company
  signclick.company.sell:
    description: Allows the player to sell shares of a company
  signclick.company.pay:
    description: Allows the player (if CEO) to pay others with the company balance
  signclick.company.spendable:
    description: Allows the player to check how much a company can still spend
  signclick.company.transfer:
    description: Allows the player to transfer shares to another player
  signclick.company.get_support:
    description: Allows the player to check who another player supports as CEO
  signclick.company.support:
    description: Allows the player to change support for CEO
  signclick.company.open_trade:
    description: Allows the player to set the company trading policy to Open Trade (infinite shares can be bought)
  signclick.company.markettop:
    description: Allows the player to see the ranking of companies based on available shares
  signclick.company.market:
    description: Allows the player to open the share market UI
  signclick.company.menu:
    description: Allows the player to open the company menu
  signclick.company.portfolio:
    description: Allows the player to retrieve their own shares portfolio
  signclick.company.transact:
    description: Allows the player to pay money from the company to another company
  signclick.company.contract:
    description: Allows the player to deal with contracts
    children:
      signclick.company.send_contract_ctc: true
      signclick.company.sign_contract_ctc: true
      signclick.company.send_contract_ctp: true
      signclick.company.sign_contract_ctp: true
      signclick.company.send_contract_ptc: true
      signclick.company.sign_contract_ptc: true
      signclick.company.get_contracts: true
  signclick.company.get_buy_price:
    description: Allows the player to get the price to buy a given amount of shares
  signclick.company.get_sell_price:
    description: Allows the player to get the earnings of selling a given amount of shares
  signclick.company.guide:
    description: Allows the player to receive a guide about the plugin

  #--------------------- Company Permissions Sub area Contracts -----------------------#
  # Permissions related to company management and interactions.                        #
  #------------------------------------------------------------------------------------#
  signclick.company.send_contract_ctc:
    description: Allows the player to deal with contracts
  signclick.company.sign_contract_ctc:
    description: Allows the player to deal with contracts
  signclick.company.send_contract_ctp:
    description: Allows the player to deal with contracts
  signclick.company.sign_contract_ctp:
    description: Allows the player to deal with contracts
  signclick.company.send_contract_ptc:
    description: Allows the player to deal with contracts
  signclick.company.sign_contract_ptc:
    description: Allows the player to deal with contracts
  signclick.company.get_contracts:
    description: Allows the player to deal with contracts

  #------------------------------ Country Permissions ---------------------------------#
  # Permissions related to country management.                                         #
  #------------------------------------------------------------------------------------#
  signclick.country.*:
    description: Allows the player country commands
    default: true
    children:
      signclick.country.create: true
      signclick.country.bal: true
      signclick.country.pay: true
      signclick.country.donate: true
      signclick.country.baltop: true
      signclick.country.tax: true
      signclick.country.invite: true
      signclick.country.accept: true
      signclick.country.kick: true
      signclick.country.info: true
      signclick.country.leave: true
      signclick.country.setspawn: true
      signclick.country.spawn: true
      signclick.country.add_enforcement: true
      signclick.country.remove_enforcement: true
      signclick.country.menu: true
      signclick.country.election: true
      signclick.country.vote: true
      signclick.country.guide: true

  #--------------------------- Country Permissions Sub area ---------------------------#
  # Permissions related to country management and interactions.                        #
  #------------------------------------------------------------------------------------#
  signclick.country.create:
    description: Allows the player to create a country
  signclick.country.bal:
    description: Allows the player to get country balance
  signclick.country.pay:
    description: Allows the player to pay as the country
  signclick.country.donate:
    description: Allows the player to give funds to the country
  signclick.country.baltop:
    description: Allows the player to get country baltop
  signclick.country.tax:
    description: Allows the player to set the country taxrate
  signclick.country.invite:
    description: Allows the player to invite other players to the country
  signclick.country.accept:
    description: Allows the player to accept a country invite
  signclick.country.kick:
    description: Allows the player to kick players from the country
  signclick.country.info:
    description: TO DO LATER
  signclick.country.leave:
    description: TO DO LATER
  signclick.country.setspawn:
    description: TO DO LATER
  signclick.country.spawn:
    description: TO DO LATER
  signclick.country.add_enforcement:
    description: TO DO LATER
  signclick.country.remove_enforcement:
    description: TO DO LATER
  signclick.country.menu:
    description: TO DO LATER
  signclick.country.election:
    description: TO DO LATER
  signclick.country.vote:
    description: TO DO LATER
  signclick.country.guide:
    description: TO DO LATER

  #--------------------------- Country Permissions Sub area Staff ---------------------#
  # Permissions related to country management and interactions.                        #
  #------------------------------------------------------------------------------------#
  signclick.country.setowner:
    description: TO DO LATER
  signclick.country.removeowner:
    description: TO DO LATER
  signclick.country.color:
    description: TO DO LATER
  signclick.country.promote:
    description: TO DO LATER
  signclick.country.demote:
    description: TO DO LATER
  signclick.country.remove:
    description: TO DO LATER
  signclick.country.addmember:
    description: TO DO LATER
  signclick.country.removemember:
    description: TO DO LATER

  signclick.company.sharebal:
    default: false
    description: Allows the player to see how much of its value depends on shares bought, instead of balance

#-------------------------------- Staff Permissions ---------------------------------#
# A parent permission for staff members, granting all plugin permissions.            #
#------------------------------------------------------------------------------------#
  signclick.staff:
    default: op
    children:
      signclick.*: true
      signclick.country.setowner: true
      signclick.country.removeowner: true
      signclick.country.color: true
      signclick.country.promote: true
      signclick.country.demote: true
      signclick.country.remove: true
      signclick.country.addmember: true
      signclick.country.removemember: true

#------------------------------------------------------------------------------------#
#                                      Dependencies                                  #
#------------------------------------------------------------------------------------#
# 'depend' lists plugins that are required for SignClick to function.                #
# 'softdepend' lists plugins that SignClick can integrate with if they are present.  #
#------------------------------------------------------------------------------------#
depend: [Vault]
softdepend: [dynmap, Essentials]

#-------------------------------------------END--------------------------------------#
