#YML used to init the default production config, in a quick manner

types:
  EASY:
    researchTime: 1800 #30m
    productionTime: 60
    COST: 5
  MEDIUM:
    researchTime: 7200 #2h
    productionTime: 120
    COST: 20
  HARD:
    researchTime: 28800 #8h
    productionTime: 300
    COST: 200
  VERY_HARD:
    researchTime: 86400 #24h
    productionTime: 1800 #30m
    COST: 10000
  LEGENDARY:
    researchTime: 172800 #48h
    productionTime: 3600 #1h
    COST: 1000000


companyTypes:
  Farmer:
    icon: WHEAT
    products:
      CARROT:
        TYPE: EASY
      POTATO:
        TYPE: EASY
      WHEAT:
        TYPE: EASY
      BEETROOT:
        TYPE: EASY
      MELON_SLICE:
        TYPE: EASY
      PUMPKIN:
        TYPE: EASY
      SUGAR_CANE:
        TYPE: MEDIUM
      CACTUS:
        TYPE: MEDIUM
      BAMBOO:
        TYPE: EASY
      KELP:
        TYPE: EASY
      VINES:
        TYPE: MEDIUM
