package com.klanting.signclick.economy;

import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.klanting.signclick.economy.companyPatent.Patent;
import com.klanting.signclick.economy.companyPatent.PatentUpgrade;
import com.klanting.signclick.economy.companyUpgrades.Upgrade;
import com.klanting.signclick.economy.contractRequests.ContractRequest;
import com.klanting.signclick.economy.logs.PluginLogs;
import org.bukkit.block.Block;
import org.bukkit.entity.Player;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

public interface CompanyI {
    Research getResearch();
    boolean hasPendingContractRequest();
    ContractRequest getPendingContractRequest();
    List<Product> getProducts();
    void addProduct(Product product);
    CompanyOwnerManager getCOM();
    double getSpendable();
    void setSpendable(double spendable);
    void setMarketShares(Integer marketShares);
    double getShareBalance();
    Integer getTotalShares();
    void setTotalShares(Integer totalShares);
    double getValue();
    double getShareBase();
    double getBal();
    boolean removeBal(double amount);
    boolean removeBal(double amount, boolean skipSpendable);
    boolean addBalNoPoint(double bal);
    void changeBase();
    double stockCompareGet();
    double stockCompare();
    Integer getMarketShares();
    boolean addBal(double amount);
    void supportUpdate(Account holder, UUID uuid);
    void checkSupport();
    void getShareTop(Player player);
    void dividend();
    void info(Player player);
    void acceptOfferCompContract();
    void sendOfferCompContract(String stock_name, double amount, int weeks, String reason);
    void receiveOfferCompContract(String stock_name, double amount, int weeks, String reason);
    void acceptOfferPlayerContract();
    void receiveOfferPlayerContract(String playerUUID, double amount, int weeks, String reason);
    boolean doUpgrade(Integer id);
    void calculateCountry();
    String getCountry();
    String getName();
    String getStockName();
    ArrayList<Upgrade> getUpgrades();
    void update(String action, String message, UUID issuer);
    String getType();
    void addShareBal(Double amount);
    void removeShareBal(Double amount);
    ArrayList<Patent> getPatent();
    void addObserver(PluginLogs observer);
    List<PluginLogs> getLogObservers();
    void setType(String type);
    ArrayList<PatentUpgrade> getPatentUpgrades();
    HashMap<Block, Machine> getMachines();
    String getPlayerNamePending();
    double getPlayerAmountPending();
    int getPlayerWeeksPending();
    void setCountry(Country country);
    CompanyI getRef();
}
